### ISSUE TITLE
The ui cannot access

### ISSUE THREAD

**Issue by zhushiyang** [srimaln91/etcd-adminer#24]
**I run with docker and report the following error：**
panic: yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into []struct { Name string; Endpoints []string "yaml:\"endpoints\""; SuperAdmin struct { UserName string "yaml:\"username\""; Password string "yaml:\"password\"" } "yaml:\"superadmin\"" }

goroutine 1 [running]:
github.com/srimaln91/etcd-adminer/bootstrap.Init()
        /tmp/etcd-adminer/api/bootstrap/init.go:27 +0xa73
main.main()
        /tmp/etcd-adminer/api/main.go:13 +0x2a

**The configuration file is as follows:**
http:
  port: 8080

logger:
  level: "DEBUG"

etcd:
- name: "LOCAL"
  endpoints:
    - "0.0.0.0:12379" 
    - "0.0.0.0:22379" 
    - "0.0.0.0:22379" 
  superadmin:
    username: root
    password: root@123

**Comment by srimaln91** [comment]
Hi @zhushiyang 

Thanks for reporting this issue. Appreciate if you can send the the .yaml file with exact indentations. So I can take a look and try to recreate the problem

**Comment by gslin** [comment]
Yeah, same issue here, with `config.yaml`:

```
http:
  port: 8080
logger:
  level: "DEBUG"
etcd:
  endpoints:
    - "10.x.0.x:2379"
    - "10.x.0.y:2379"
    - "10.x.0.z:2379"
  superadmin:
    username: "root"
    password: "x"
```

My `docker-compose.yaml`:

```
version: '3.2'
services:
  etcd-adminer:
    image: srimaln91/etcd-adminer:latest
    container_name: etcd-adminer
    hostname: etcd-adminer
    ports:
      - 8001:8080
    restart: unless-stopped
    volumes:
      - /srv/x/config.yaml:/app/config.yaml
```

Also the image id:

```
REPOSITORY               TAG       IMAGE ID       CREATED         SIZE
srimaln91/etcd-adminer   latest    0ef29d0d9912   12 months ago   29.1MB
```

Logs from `docker compose logs`:

```
etcd-adminer  | goroutine 1 [running]:
etcd-adminer  | github.com/srimaln91/etcd-adminer/bootstrap.Init()
etcd-adminer  |         /tmp/etcd-adminer/api/bootstrap/init.go:27 +0xa73
etcd-adminer  | main.main()
etcd-adminer  |         /tmp/etcd-adminer/api/main.go:13 +0x2a
etcd-adminer  | panic: yaml: unmarshal errors:
etcd-adminer  |   line 6: cannot unmarshal !!map into []struct { Name string; Endpoints []string "yaml:\"endpoints\""; SuperAdmin struct { UserName string "yaml:\"username\""; Password string "yaml:\"password\"" } "yaml:\"superadmin\"" }
```

**Comment by gslin** [comment]
Okay, after reading Golang code and asking ChatGPT, the cluster needs to be assigned with `name`, e.g.:

```yaml
http:
  port: 8080
logger:
  level: "DEBUG"
etcd:
  - name: "etcd-cluster"
    endpoints:
      - "10.1.0.x:2379"
      - "10.1.0.y:2379"
      - "10.1.0.z:2379"
    superadmin:
      username: "root"
      password: "x"
```

I guess it's because this issue author and I did the same mistake, copying sample from `README.md`, not from the correct/working `config.default.yaml` in the repository.
